export enum DocumentStatus {
  DRAFT = 'DRAFT',
  ISSUED_FOR_REVIEW = 'ISSUED_FOR_REVIEW',
  ISSUED_FOR_APPROVAL = 'ISSUED_FOR_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUPERSEDED = 'SUPERSEDED',
  VOID = 'VOID',
}
